### PR TITLE
#5 Create a custom scrollbar

### PR DESCRIPTION
**Pull request by VaibhavTalkhande**
## Fixes Issue

This PR fixes the following issues:
fixes - #5

#example
Added custom scrollbar

## Changes proposed

Here comes all the changes proposed through this PR

## Check List (Check all the boxes which are applicable) 

- [ X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X ] All new and existing tests passed.
- [ X] This PR does not contain plagiarized content.
- [ X] The title of my pull request is a short description of the requested changes.

## Screenshots and video
Screenshot (4)

Add all the screenshots and a video which support your changes

### CODE REVIEW

**Comment by mnnkhndlwl** [comment]
bro your commit exposes env files
which is not good for security

**Comment by mnnkhndlwl** [comment]
some one can easily look on old commits and secret keys will be exposed

**Comment by mnnkhndlwl** [comment]
you should have saved env files of server and client as .env only
no need for client.env and server.env

**Comment by mnnkhndlwl** [comment]
one thing you can do is stash theme commits and then make required changes

**Comment by VaibhavTalkhande** [comment]
Ok

**Comment by VaibhavTalkhande** [comment]
Other than is there any changes i need to do

**Pull request closed without merging**
