### PR TITLE
centered loading spinner

### PR DESCRIPTION
**Pull request by arjunchoudhury07**
## Fixes Issue
#21 
This PR fixes the following issues:

#example

## Changes proposed

Here comes all the changes proposed through this PR

## Check List (Check all the boxes which are applicable) 

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots and video
spinner

Add all the screenshots and a video which support your changes

### CODE REVIEW

**Comment by mnnkhndlwl** [comment]
can you show the screenshot of login / signup page to confirm that this spinner is also aligned at center on that page also

**Comment by mnnkhndlwl** [comment]
Fix it bro

**Comment by arjunchoudhury07** [comment]
resolved #21 
centered in signin page
spinner3

**Comment by mnnkhndlwl** [comment]
bro bhohot sahi lag rha hai spinner good job 👍👍

**Pull request merged**
